apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ntando-miya
spec:
  profile:
    displayName: Ntando Miya
    email: ntandomiya97@gmail.com
  memberOf: [genuvia]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: genuvia
spec:
  type: organization
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: genuvia
  description: Genuvia Intelligence Infrastructure
spec:
  owner: user:ntando-miya
